web:
    image: nginx:latest    
    ports:
        - "80:80"
    volumes:
        - ../:/www
        - ./config/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:    
    build: .
    volumes:
        - ../:/www
    links: 
        - postgres
        - mongo
postgres:
    image: postgres:9.5
    ports:
        - "5432:5432"
    environment:
        POSTGRES_PASSWORD: docker
        POSTGRES_USER: docker
mongo:
    image: mongo:3.4
    ports:
        - "27017:27017"
